CREATE TABLE tb_vereador(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
cpf VARCHAR(14) NOT NULL,
logradouro VARCHAR(255) NOT NULL,
numero VARCHAR(255) NOT NULL,
complemento VARCHAR(255),
cep VARCHAR(8) NOT NULL,
telefone VARCHAR (255) NOT NULL,
partido_sigla VARCHAR(10) NOT NULL,
partido_nome VARCHAR(255) NOT NULL,
projeto_lei INTEGER NOT NULL,
processo INTEGER NOT NULL,
foto VARCHAR(64) NOT NULL);